defaults:
  - image_transforms: default
  - _self_

# Data
video: False
data_path: "demos/pusht"
data_name: "lerobot/pusht"
log_dir: "logs"
ckpt_save_path: "ckpts"
misc_save_path: "misc"

# Training hyperparams
is_debug: true
epochs: 400
batch_size: 128   # this is per device if ddp is used
grad_clip_norm: 10.
seed: 123
port: 12338
devices: [0]
strategy: cuda  # [cuda, ddp, fsdp]; cuda is single gpu, ddp is data multigpu, fsdp is model & data different gpus
val_every: 10
save_every: 20
save_max: 3

# Prediction setup
#n_action_steps: 8  # execution horizon
#n_obs_steps: 1    # Use 0 for unconditional generation -- not used during training
#horizon: 128  # prediction horizon -- what the actual model predicts
n_obs_steps: 2
horizon: 16
n_action_steps: 8

# Policy options
model_type: src.hackathon_distillation.policy.ddpm_wrapper.DdpmWrapper  #FlowMatchingWrapper
num_inference_steps: 10   # How many steps are used for denoising during inference; if null this is eq. to num of train steps
do_mask_loss_for_padding: false
drop_n_last_frames: True
prediction_type: "epsilon"

# Network
network:
  dropout: 0.
  down_dims: [ 512, 1024, 2048 ]
  input_shapes: {
    "obs.img": [3, 96, 96],  # comment out for no images
    "obs.state": [ 2 ],
  }
  input_normalization_modes: {
    "obs.img": "mean_std",
    "obs.state": "min_max",
  }
  output_shapes: {
    "action": [ 2 ],  # Note we need feature dim first! Find out why and how this works; feature dim is ndof
  }
  output_normalization_modes: {
    "action": "min_max",
  }
  pretrained_backbone_weights: null #'DEFAULT'    # comment out for no pretrained backbone
  use_group_norm: True
  n_groups: 8
  vision_backbone: resnet18
  crop_shape: [ 84, 84 ]
  crop_is_random: True
  spatial_softmax_num_keypoints: 32

  # Unet.
  network_cls: hackathon_distillation.networks.unet.ConditionalUnet1d
  kernel_size: 5
  diffusion_step_embed_dim: 128
  use_film_scale_modulation: True

noise_scheduler:
  _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler

  num_train_timesteps: 10
  beta_schedule: squaredcos_cap_v2
  beta_start: 0.0001
  beta_end: 0.02
  prediction_type: epsilon # epsilon / sample
  clip_sample: True
  clip_sample_range: 1.0

optimizer:
  _target_: torch.optim.AdamW
  kwargs:
    lr: 5e-4  # defaults to 0.0025
    # betas: [ 0.95, 0.999 ]
    eps: 1e-8
    weight_decay: 1e-6
    # warmup_steps: 500
